rvm: '2.5.0'

services:
  - postgresql

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3


before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql chitter_test -U postgres -c 'CREATE TABLE peeps(id SERIAL PRIMARY KEY, text VARCHAR(240));'
  # - psql chitter_test -U postgres -c 'ALTER TABLE peeps ADD COLUMN posted_time VARCHAR(60);'
  # - psql chitter_test -U postgres -c 'CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(60), email VARCHAR(60), username VARCHAR(60), password VARCHAR(140));'
  # - psql chitter_test -U postgres -c 'ALTER TABLE peeps ADD COLUMN user_id INTEGER REFERENCES users (id);'
  # - psql chitter_test -U postgres -c 'CREATE TABLE comments(id SERIAL PRIMARY KEY, text VARCHAR(240), peep_id INTEGER REFERENCES peeps (id), user_id INTEGER REFERENCES users (id)); '
